from tkinter import *
root=Tk()
root.title("Bus Booking")
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry("%dx%d+0+0"%(w,h))
bus=PhotoImage(file='.\\python_bus.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Online Bus Booking System',bg='light blue',fg='red',font='Arial 20 bold').grid(row=1,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Add Bus Details',bg='floral white',fg='green3',font='Arial 16 bold').grid(row=2,column=0,pady=20,columnspan=15,padx=w//2.5)
Label(root,text='Bus ID',fg='grey1',font='Arial 12').grid(row=3,column=0,pady=50)
e=Entry(root)
e.grid(row=3,column=1)
bus_type=StringVar()
option=("AC 2X2","AC 3X2","Non AC 2X2","Non AC 3X2","AC-Sleeper 2X1","Non-AC Sleeper 2X1")
menu=OptionMenu(root,bus_type,*option)
menu.grid(row=3,column=3)
bus_type.set("Select Bus Type")
Label(root,text='Bus Type',fg='grey1',font='Arial 12').grid(row=3,column=2)
Label(root,text='Capacity',fg='grey1',font='Arial 12').grid(row=3,column=4)
g=Entry(root)
g.grid(row=3,column=5)
Label(root,text='Fare Rs',fg='grey1',font='Arial 12').grid(row=3,column=6)
h=Entry(root)
h.grid(row=3,column=7)
Label(root,text='Operator ID',fg='grey1',font='Arial 12').grid(row=3,column=8)
i=Entry(root)
i.grid(row=3,column=9)
Label(root,text='Route id',fg='grey1',font='Arial 12').grid(row=3,column=10)
j=Entry(root)
j.grid(row=3,column=11)

Button(root,text='Add Bus',bg='lawn green',fg='grey1').grid(row=5,column=4,pady=20,columnspan=4)
Button(root,text='Edit Bus',bg='lawn green',fg='grey1').grid(row=5,column=5,pady=20,columnspan=4)
home=PhotoImage(file='.\\home.png')
Label(root,image=home).grid(row=5,column=6,columnspan=3)
root.mainloop()
