from tkinter import *
root=Tk()
root.title("Bus Booking")
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry("%dx%d+0+0"%(w,h))
bus=PhotoImage(file='.\\python_bus.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Online Bus Booking System',bg='light blue',fg='red',font='Arial 20 bold').grid(row=1,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Add Bus Running Details',bg='floral white',fg='green3',font='Arial 16 bold').grid(row=2,column=0,pady=20,columnspan=15)
Label(root,text='Bus ID',fg='grey1',font='Arial 12').grid(row=3,column=0,pady=50)
o=Entry(root)
o.grid(row=3,column=1,padx=50)
Label(root,text='Running Date',fg='grey1',font='Arial 12').grid(row=3,column=2)
p=Entry(root)
p.grid(row=3,column=3,padx=50)
Label(root,text='Seat Available',fg='grey1',font='Arial 12').grid(row=3,column=4)
q=Entry(root)
q.grid(row=3,column=5,padx=50)
Button(root,text='Add Run',bg='lawn green',fg='grey1').grid(row=3,column=6,pady=20,padx=10)
Button(root,text='Delete Run',bg='lawn green',fg='grey1').grid(row=3,column=7,pady=20,padx=10)
home=PhotoImage(file='.\\home.png')
Button(root,image=home).grid(row=4,column=6)
root.mainloop()

