from tkinter import *
root=Tk()
root.title("Bus Booking")
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry("%dx%d+0+0"%(w,h))
bus=PhotoImage(file='.\\python_bus.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Online Bus Booking System',bg='light blue',fg='red',font='Arial 20 bold').grid(row=1,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Check Your Booking',fg='dark green',bg='green2',font='Arial 18 bold').grid(row=3,column=0,pady=20,columnspan=15)
Label(root,text='Enter Your Mobile No:',fg='grey1',font='Arial 12').grid(row=4,column=5)
d=Entry(root)
d.grid(row=4,column=6)
Button(root,text='Check Booking').grid(row=4,column=7)
home=PhotoImage(file='.\\home.png')
Button(root,image=home).grid(row=4,column=9)
root.mainloop()
