from tkinter import *
root=Tk()
root.title("Bus Booking")
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry("%dx%d+0+0"%(w,h))
def proceedbook():
    frame2=Frame(root)
    frame2.grid(row=7,column=0,columnspan=20,pady=h//30)
    Label(frame2,text='Fill Passenger Detail to book the bus ticket',bg='lightblue',fg='red',font='Arial 16 bold').grid(row=6,column=0,padx=w//2.5,columnspan=20,pady=h//30)
    Label(frame2,text='Name',font='Arial 12 bold').grid(row=8,column=1)
    Entry(frame2).grid(row=8,column=2)
    Label(frame2,text='Gender',font='Arial 12 bold').grid(row=8,column=3)
    gender=StringVar()
    gender.set('Male')
    option=('male','female')
    menu=OptionMenu(frame2,gender,*option)
    menu.grid(row=8,column=4)
    Label(frame2,text='No of Seats',font='Arial 12 bold').grid(row=8,column=5)
    Entry(frame2).grid(row=8,column=6)
    Label(frame2,text='Mobile No',font='Arial 12 bold').grid(row=8,column=7)
    Entry(frame2).grid(row=8,column=8)
    Label(frame2,text='Age',font='Arial 12 bold').grid(row=8,column=9)
    Entry(frame2).grid(row=8,column=10)
    button1=Button(frame2,text='Book Seat',font='Arial 12 bold',bg='lightgreen')
    button1.grid(row=8,column=11)
def show():
    frame1=Frame(root)
    frame1.grid(row=4,column=0,columnspan=20,pady=h//30)
    Label(frame1,text='Select Bus',font='Arial 12 bold',fg='green').grid(row=4,column=0)
    Label(frame1,text='Operator',font='Arial 12 bold',fg='green').grid(row=4,column=2)
    Label(frame1,text='Bus Type',font='Arial 12 bold',fg='green').grid(row=4,column=4)
    Label(frame1,text='AvailableCapacity',font='Arial 12 bold',fg='green').grid(row=4,column=6)
    Label(frame1,text='Fare',font='Arial 12 bold',fg='green').grid(row=4,column=8)
    Label(frame1,text='Bus 1',font='Arial 12 bold',fg='black',bg='lightblue').grid(row=5,column=0)
    Label(frame1,text='Kamla',font='Arial 12  italic',fg='blue').grid(row=5,column=2)
    Label(frame1,text='AC 2x2',font='Arial 12 bold',fg='blue').grid(row=5,column=4)
    Label(frame1,text='25/30',font='Arial 12 bold',fg='blue').grid(row=5,column=6)
    Label(frame1,text='1000',font='Arial 12 bold',fg='blue').grid(row=5,column=8)
    Button(root,text='Proceed to Book',font='Arial 12 bold',bg='lightgreen',command=proceedbook).grid(row=4,column=11)
frame3=Frame(root)
frame3.grid(row=3,column=0,columnspan=20,pady=h//30)
bus=PhotoImage(file='.\\python_bus.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Online Bus Booking System',bg='light blue',fg='red',font='Arial 20 bold').grid(row=1,column=0,columnspan=15,padx=w//2.5)
Label(root,text='Enter Journey Details',bg='green2',fg='dark green',font='Arial 16 bold').grid(row=2,column=0,columnspan=15,padx=w//2.5,pady=h//30)
Label(frame3,text='To',fg='grey1',font='Arial 12').grid(row=3,column=2)
a=Entry(frame3)
a.grid(row=3,column=3)
Label(frame3,text='From',fg='grey1',font='Arial 12').grid(row=3,column=4)
b=Entry(frame3)
b.grid(row=3,column=5)
Label(frame3,text='Journey Date',fg='grey1',font='Arial 12').grid(row=3,column=6)
c=Entry(frame3)
c.grid(row=3,column=7)
Button(frame3,text='Show Bus',bg='green3',command=show).grid(row=3,column=8)
home=PhotoImage(file='.\\home.png')
Button(root,image=home).grid(row=3,column=11)

root.mainloop()
